name: CI + CD Pipeline

on:
  push:
    branches:
      - feature/mlflow-cd
      - main
  pull_request:
    branches:
      - feature/mlflow-cd
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/upload-artifact@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Run tests
        run: pytest -q --disable-warnings

      - name: Lint with flake8
        run: flake8 .

      - name: Set MLFLOW_TRACKING_URI env
        run: echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV

      - name: Train & tune model
        run: python -m src.tune_and_train

      - name: Run batch prediction
        run: python -m src.predict

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/best_model.pkl

      - name: Upload batch results
        uses: actions/upload-artifact@v4
        with:
          name: batch-prediction-results
          path: batch_prediction_dataset/results.csv

      - name: Upload prediction report
        uses: actions/upload-artifact@v4
        with:
          name: batch-prediction-report
          path: batch_prediction_dataset/report.txt

      - name:  Pipeline completed
        run: echo " CI/CD pipeline finished successfully."
